Branch week7 documentation
AY2223S1-CS2103T-W15-1/tp pull request #21
Opened 2022-09-24 14:39 UTC by ChongCheeKaiClarence

Update User Guide
Add placeholder image and skeletal Project Portfolio Page

2022-09-24 20:38 UTC, Eugene-Ong-W-X requested changes
Some fixes need to be made before merging.

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/team/chongcheekaiclarence.md
> +* **Code contributed**: [RepoSense link](https://github.com/AY2223S1-CS2103T-W15-1/tp/pulls?q=is%3Apr+author%3AChongCheeKaiClarence)
The RepoSense link here is incorrect. Please refer back to the 2103T instructions. You can also refer to the other PPPs for what the correct link looks like.

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/UserGuide.md
> +* `Name` is the name of the contact to add `TAG` to.
`Name` here should be `NAME` as per line 139

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/UserGuide.md
> +**tag add** | `tag add n/NAME t/TAG` <br> e.g., `tag add n/John Doe t/friend`
`tag create`, `tag edit`, `tag add` should be properly capitalised as per the other commands in the Command Summary

Suggestions: `Create Tag`, `Edit Tag`, `Add Tag` note that the first word is a verb

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/DeveloperGuide.md
> +    * 1a1. SoConnect updates the selection of possible words.
After each extension, it should be stated how the use case progresses.

For example for this extension, it should be `Use case resumes from step 3.`

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/DeveloperGuide.md
> +* 2a. The list is empty.
This should be `1a.` instead as it is an alternative scenario to `2.`

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/DeveloperGuide.md
> +
The MSS should end here but the end statement is missing

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/DeveloperGuide.md
> +* 2a. There are no tags.
Again, this should be `1a.` as it is an alternative to `2.`

2022-09-24 20:38 UTC, Eugene-Ong-W-X commented on docs/DeveloperGuide.md
> +    * 1a1. SoConnect shows an error message.
Is this a typo? Shouldn't it be `3a1` as this extension is listed under `3a`?

2022-09-25 06:40 UTC, ChongCheeKaiClarence commented
Made updates requested. Please check. Thanks!

2022-09-25 06:50 UTC, ChongCheeKaiClarence commented
I made the changes. Please do help to check. Thanks!

2022-09-25 07:06 UTC, Eugene-Ong-W-X approved these changes

2022-09-25 07:07 UTC, Eugene-Ong-W-X commented
LGTM

2022-09-25 07:08 UTC, merged